### ISSUE TITLE
Test JWT authentication/authorization

### ISSUE THREAD

**Issue by kenankd** [nedimkrupalija/POS-app-backend-tim56#16]

**Comment by scomor55** [comment]
**Test Scenario: JWT Authentication and Authorization**

**Description:**
This scenario tests the functionality of JWT authentication and authorization middleware in the application.

**Preconditions:**
The application is running.
The JWT secret key is properly configured.
The necessary controllers and middleware for JWT handling are implemented.

**Test Steps:**
Generate Valid JWT Token:

Action: Generate a valid JWT token for a user with admin role.
Expected Outcome: The generated token should contain the correct user role and username.

Authorize Valid JWT Token:

Action: Send a request with a valid JWT token for a user with admin role.
Expected Outcome: The request should be successfully authorized, and the user's role and username should be extracted from the token.

Return 401 for Invalid JWT Token:

Action: Send a request with an invalid JWT token.
Expected Outcome: The server should respond with a status code of 401 (Unauthorized) and a message indicating authentication failure.

Authorize Valid JWT Token for Role "User":

Action: Send a request with a valid JWT token for a user with a "user" role.
Expected Outcome: The request should be successfully authorized, and the user's role and username should be extracted from the token.

Return 401 for Missing JWT Token:

Action: Send a request without including a JWT token in the headers.
Expected Outcome: The server should respond with a status code of 401 (Unauthorized) and a message indicating authentication failure.

Return 401 for Expired JWT Token:

Action: Send a request with an expired JWT token.
Expected Outcome: The server should respond with a status code of 401 (Unauthorized) and a message indicating authentication failure.

Return 401 for JWT Token with Modified Payload:

Action: Send a request with a JWT token whose payload has been modified.
Expected Outcome: The server should respond with a status code of 401 (Unauthorized) and a message indicating authentication failure.

**Test Data:**
User with admin role: { role: 'admin', username: 'testuser' }
User with user role: { role: 'user', username: 'testuser' }
Invalid JWT token: 'invalid_token'
Modified JWT token: [Generated modified JWT token]
