### ISSUE TITLE
Routes for finishing orders

### ISSUE THREAD

**Issue by nedimkrupalija** [nedimkrupalija/POS-app-backend-tim56#92]
Going from order to invoice deducts item from storage

**Comment by zlendo1** [comment]
What routes should go into this and what should be their function? Also, is this a new model?

**Comment by nedimkrupalija** [comment]
There is existing route for order that has deduction of items from storage. Now that route should only contain creating order, and this new route should contain code for deduction of items from storage. No new model is necessary because model of order contains vat, total etc.
